version: '3.9'

volumes:
  postgressql_data:
  backup_postgressql_data:

services:

  postgressql:
    #image: postgres:12-bullseye 
    image: postgres:12
    container_name: postgressql
    environment:
      - PGDATA=/var/lib/postgresql/data/
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgressql_data:/var/lib/postgresql/data
      - backup_postgressql_data:/backup
      - ./config:/docker-entrypoint-initdb.d
    network_mode: "host"
